export enum Constraints {
  JWT_SECRET = 'JWT_SECRET',
  REFRESH_JWT_SECRET = 'REFRESH_JWT_SECRET',
  ACCESS_TOKEN_EXPIRATION = 'ACCESS_TOKEN_EXPIRATION',
  REFRESH_TOKEN_EXPIRATION = 'REFRESH_TOKEN_EXPIRATION',
}
